# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblepayLastBlocksModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='overview_biblepaylastblocksmodel', serialize=False, to='cms.CMSPlugin')),
                ('entries_count', models.IntegerField(default=8)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
