# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('gobjectid', models.CharField(max_length=100)),
                ('hex_string', models.TextField(default='')),
                ('network', models.CharField(default='unknown', max_length=20)),
                ('name', models.CharField(default='', max_length=250)),
                ('receive_address', models.CharField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('url', models.CharField(default='', max_length=250)),
                ('expense_type', models.CharField(choices=[('unknown', 'UNKNOWN'), ('charity', 'Charity'), ('pr', 'PR'), ('p2p', 'P2P'), ('it', 'IT')], default='unknown', max_length=10)),
                ('unix_starttime', models.IntegerField(default=0)),
                ('unix_endtime', models.IntegerField(default=0)),
                ('prepare_time', models.DateTimeField(default=None, null=True)),
                ('submit_time', models.DateTimeField(default=None, null=True)),
                ('trigger_time', models.DateTimeField(default=None, null=True)),
                ('paid_time', models.DateTimeField(default=None, null=True)),
                ('funded_time', models.DateTimeField(default=None, null=True)),
                ('prepare_txid', models.CharField(default='', max_length=100)),
                ('submit_txid', models.CharField(default='', max_length=100)),
                ('superblock_txid', models.CharField(default='', max_length=100)),
                ('height', models.IntegerField(default=None, null=True)),
                ('trigger_txid', models.CharField(max_length=100)),
                ('prepared', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('abstain_count', models.IntegerField(default=0)),
                ('absolute_yes_count', models.IntegerField(default=0)),
                ('masternode_count', models.IntegerField(default=0)),
            ],
        ),
    ]
