# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
