# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masternodes', '0003_auto_20180520_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masternodehistory',
            name='txid',
        ),
        migrations.AddField(
            model_name='masternodehistory',
            name='masternode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masternodes.Masternode'),
            preserve_default=False,
        ),
    ]
