# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailalert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
