# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rac', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('maschine_count', models.IntegerField(default=0)),
                ('total_procs', models.IntegerField(default=0)),
                ('task_turnaround', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RosettaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='UNKNOWN', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='rosettauser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podc.RosettaUser'),
        ),
    ]
