# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='maschine_count',
            new_name='machine_count',
        ),
    ]
