# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podc', '0002_auto_20180317_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superblock',
            fields=[
                ('height', models.IntegerField(primary_key=True, serialize=False)),
                ('total_rac', models.IntegerField(default=0)),
                ('receiver_count', models.IntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='SuperblockReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('cpid', models.CharField(max_length=100)),
                ('team', models.IntegerField(default=0)),
                ('magnitude', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('utxo_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('utxo_weight', models.IntegerField(default=0)),
                ('task_weight', models.IntegerField(default=0)),
                ('avg_rac', models.IntegerField(default=0)),
                ('modified_rac', models.IntegerField(default=0)),
                ('unbanked', models.BooleanField(default=False)),
                ('machine_count', models.IntegerField(default=0)),
                ('total_procs', models.IntegerField(default=0)),
                ('rosettauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podc.RosettaUser')),
                ('superblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podc.Superblock')),
            ],
        ),
    ]
