# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podc', '0004_auto_20180318_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosettauser',
            name='leaderboard_pos',
            field=models.IntegerField(default=0),
        ),
    ]
