# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podc', '0005_rosettauser_leaderboard_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='superblockreceiver',
            name='reward',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
